CREATE TABLE [HMS_USERS] (
  [ID_USER] INTEGER PRIMARY KEY,
  [USERNAME] VARCHAR2(50),
  [EMAIL] VARCHAR2(100),
  [FIRST_NAME] VARCHAR2(50),
  [LAST_NAME] VARCHAR2(50),
  [ADDRESS] VARCHAR2(200),
  [CITY] VARCHAR2(50),
  [ZIPCODE] VARCHAR2(10),
  [COUNTRY] VARCHAR2(50),
  [PHONE] VARCHAR2(20),
  [CREATED_AT] TIMESTAMP
)
GO

CREATE TABLE [HMS_TRANSPORTATION] (
  [ID_COMPANY] INTEGER PRIMARY KEY,
  [NAME] VARCHAR2(50),
  [ADDRESS] VARCHAR2(200),
  [EMAIL] VARCHAR2(100),
  [PHONE] VARCHAR2(100)
)
GO

CREATE TABLE [HMS_PRODUCTS] (
  [ID_PRODUCT] INTEGER,
  [ID_CATEGORY] INTEGER,
  [DESCRIPTION] VARCHAR2(200),
  [PRICE] INTEGER,
  [TOTAL_ITEMS] INTEGER,
  PRIMARY KEY ([ID_PRODUCT], [ID_CATEGORY])
)
GO

CREATE TABLE [HMS_ORDERS] (
  [ID_ORDER] INTEGER,
  [ID_TRANSPORTATION] INTEGER,
  [ID_CUSTOMER] INTEGER,
  [ORDER_DATE] TIMESTAMP,
  PRIMARY KEY ([ID_ORDER], [ID_TRANSPORTATION], [ID_CUSTOMER])
)
GO

CREATE TABLE [HMS_ORDER_ITEMS] (
  [ID_ORDER_ITEM] INTEGER,
  [ID_ORDER] INTEGER,
  [ID_PRODUCT] INTEGER,
  [QUANTITY] INTEGER,
  PRIMARY KEY ([ID_ORDER_ITEM], [ID_ORDER], [ID_PRODUCT])
)
GO

CREATE TABLE [HMS_FEEDBACKS] (
  [ID_FEEDBACK] INTEGER,
  [ID_PRODUCT] INTEGER,
  [ID_USER] INTEGER,
  [TITLE] VARCHAR2(200),
  [MESSAGE] VARCHAR2(200),
  [CREATED_DATE] TIMESTAMP,
  PRIMARY KEY ([ID_FEEDBACK], [ID_PRODUCT], [ID_USER])
)
GO

CREATE TABLE [HMS_CATEGORIES] (
  [ID_CATEGORY] INTEGER PRIMARY KEY,
  [NAME] INTEGER,
  [DESCRIPTION] INTEGER
)
GO

ALTER TABLE [HMS_ORDERS] ADD FOREIGN KEY ([ID_CUSTOMER]) REFERENCES [HMS_USERS] ([ID_USER])
GO

ALTER TABLE [HMS_ORDER_ITEMS] ADD FOREIGN KEY ([ID_ORDER]) REFERENCES [HMS_ORDERS] ([ID_ORDER])
GO

ALTER TABLE [HMS_TRANSPORTATION] ADD FOREIGN KEY ([ID_COMPANY]) REFERENCES [HMS_ORDERS] ([ID_TRANSPORTATION])
GO

ALTER TABLE [HMS_PRODUCTS] ADD FOREIGN KEY ([ID_CATEGORY]) REFERENCES [HMS_CATEGORIES] ([ID_CATEGORY])
GO

ALTER TABLE [HMS_USERS] ADD FOREIGN KEY ([ID_USER]) REFERENCES [HMS_FEEDBACKS] ([ID_USER])
GO

ALTER TABLE [HMS_PRODUCTS] ADD FOREIGN KEY ([ID_PRODUCT]) REFERENCES [HMS_FEEDBACKS] ([ID_PRODUCT])
GO
