CREATE OR REPLACE VIEW OLAP_DIM_ORDER_CATEGORY AS 
SELECT 
    O.ID_CUSTOMER as CUSTOMER_ID,
    O.ID_ORDER as ID_ORDER,
    I.ID_PRODUCT as ID_PRODUCT,
    C.ID_CATEGORY as ID_CATEGORY,
    C.NAME as CATEGORY_NAME
FROM HMS_ORDERS_VIEW O 
INNER JOIN HMS_ORDER_ITEMS_VIEW I ON O.ID_ORDER = I.ID_ORDER 
INNER JOIN HMS_PRODUCTS_VIEW P ON I.ID_PRODUCT = P.ID_PRODUCT 
INNER JOIN HMS_CATEGORIES C ON C.ID_CATEGORY = P.ID_CATEGORY;


SELECT * FROM OLAP_DIM_ORDER_CATEGORY;


CREATE OR REPLACE VIEW OLAP_DIM_ORDER_CITY AS 
SELECT 
    O.ID_CUSTOMER as CUSTOMER_ID,
    O.ID_ORDER as ID_ORDER,
    C.NAME as CITY
FROM HMS_ORDERS_VIEW O 
INNER JOIN HMS_USERS_VIEW U ON U.ID_USER = O.ID_CUSTOMER 
INNER JOIN HMS_CITIES_VIEW C ON C.NAME = U.CITY;

SELECT * FROM OLAP_DIM_ORDER_CITY;


-- ok, developer OLAP_DIM_CUST_ORDER_TRANSPORTATION
CREATE OR REPLACE VIEW OLAP_DIM_CUST_ORDER_TRANSPORTATION AS 
SELECT 
    O.ID_CUSTOMER as CUSTOMER_ID,
    O.ID_ORDER as ID_ORDER,
    T.ID_COMPANY as ID_COMPANY,
    T.NAME as TRANSPORTATION_NAME
FROM HMS_ORDERS_VIEW O
INNER JOIN HMS_TRANSPORTATION_VIEW T ON T.ID_COMPANY = O.ID_TRANSPORTATION;


SELECT * FROM OLAP_DIM_CUST_ORDER_TRANSPORTATION;


-- ok, developer: OLAP_DIM_CUSTOMER_ORDER_ITEM_FEEDBACK_POSITIVE
CREATE OR REPLACE VIEW OLAP_DIM_CUSTOMER_ORDER_ITEM_FEEDBACK_POSITIVE AS 
SELECT 
    O.ID_CUSTOMER as CUSTOMER_ID,
    I.ID_ORDER_ITEM as ID_ORDER_ITEM,
    F.ID_FEEDBACK as ID_FEEDBACK,
    F.RATING as RATING,
    F.MESSAGE as MESSAGE
FROM HMS_ORDERS_VIEW O 
INNER JOIN HMS_ORDER_ITEMS_VIEW I ON O.ID_ORDER = I.ID_ORDER 
INNER JOIN HMS_FEEDBACKS_VIEW F ON F.ID_ORDER_ITEM = I.ID_ORDER_ITEM
WHERE F.RATING LIKE 1;


SELECT * FROM OLAP_DIM_CUSTOMER_ORDER_ITEM_FEEDBACK_POSITIVE;

-- OK, SYS: OLAP_DIMENSION_CATEGORY_ORDER
DROP VIEW OLAP_DIMENSION_CATEGORY_ORDER;
CREATE OR REPLACE VIEW OLAP_DIMENSION_CATEGORY_ORDER AS
SELECT
    C.ID_CATEGORY,
    C.NAME AS CATEGORY_NAME,
    O.ID_ORDER,
    O.ORDER_DATE,
    O.ID_CUSTOMER,
    O.ID_TRANSPORTATION,
    P.PRODUCT_NAME,
    P.PRICE
FROM HMS_ORDERS_VIEW O 
INNER JOIN
    HMS_ORDER_ITEMS_VIEW I ON I.ID_ORDER = O.ID_ORDER
INNER JOIN
    HMS_PRODUCTS_VIEW P ON I.ID_PRODUCT = P.ID_PRODUCT
INNER JOIN
    HMS_CATEGORIES C ON C.ID_CATEGORY  = P.ID_CATEGORY;
    
SELECT * FROM OLAP_DIMENSION_CATEGORY_ORDER;


-- OK, DEVELOPER: OLAP_DIMENSION_CATEGORY_ORDER
CREATE OR REPLACE VIEW OLAP_DIMENSION_CATEGORY_ORDER AS
SELECT * FROM sys.OLAP_DIMENSION_CATEGORY_ORDER;

SELECT * FROM OLAP_DIMENSION_CATEGORY_ORDER;