CREATE OR REPLACE VIEW OLAP_VIEW_ORDER_CATEGORY AS
SELECT
CASE
 WHEN GROUPING(D.CATEGORY_NAME) = 1 THEN '{Total General}'
 ELSE D.CATEGORY_NAME END AS CATEGORY_NAME,
CASE
 WHEN GROUPING(D.CATEGORY_NAME) = 1 THEN ' '
 WHEN GROUPING(D.CUSTOMER_ID) = 1 THEN 'subtotal category ' || D.CATEGORY_NAME
 ELSE D.CUSTOMER_ID END AS CUSTOMER_ID,
 SUM(NVL(f.TOTAL_SALES_AMOUNT, 0)) as SALES_AMOUNT
FROM OLAP_DIM_ORDER_CATEGORY D
 INNER JOIN OLAP_FACTS_SALES_AMOUNT F ON D.CUSTOMER_ID = F.ID_CUSTOMER
GROUP BY ROLLUP (D.CATEGORY_NAME, D.CUSTOMER_ID)
ORDER BY D.CATEGORY_NAME, D.CUSTOMER_ID;
 
SELECT * FROM OLAP_VIEW_ORDER_CATEGORY;


CREATE OR REPLACE VIEW OLAP_VIEW_TOTAL_SALES_CITIES AS
SELECT C.CITY, SUM(NVL(f.TOTAL_SALES_AMOUNT, 0)) AS TOTAL_AMOUNT_CITY 
FROM OLAP_FACTS_SALES_AMOUNT_VIEW F 
INNER JOIN OLAP_DIM_ORDER_CITY C ON C.CUSTOMER_ID = F.ID_CUSTOMER 
GROUP BY C.CITY;

SELECT * FROM OLAP_VIEW_TOTAL_SALES_CITIES;
